 - type: web
    name: n8n-climatrack
    runtime: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: N8N_HOST
        value: n8n-climatrack.onrender.com

      - key: WEBHOOK_URL
        value: https://n8n-climatrack.onrender.com/

      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo

      - key: TZ
        value: America/Sao_Paulo

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-climatrack-db
          property: host

      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-climatrack-db
          property: port

      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-climatrack-db
          property: database

      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-climatrack-db
          property: user

      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-climatrack-db
          property: password

databases:
  - name: n8n-climatrack-db
    plan: free
    databaseName: n8n
    user: n8n
