services:
  - type: web
    name: climatrack-n8n-app
    runtime: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_PORT
        value: 5678

      - key: PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: N8N_HOST
        value: climatrack-n8n-app.onrender.com

      - key: WEBHOOK_URL
        value: https://climatrack-n8n-app.onrender.com/

      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo

      - key: TZ
        value: America/Sao_Paulo

      - key: N8N_ENCRYPTION_KEY
        generateValue: true
